version: "3.8"

# Chatbot: add file description
services:
  # Chatbot: add service description
  server:
    image: lehcode/soakp:1.0.1
    container_name: ${CONTAINER_NAME:-soakp-server}
    hostname: ${SERVER_HOST:-soakp-server}
    command: /init.sh
    build:
      context: .
      dockerfile: Dockerfile
      args:
        workdir: ${WORKDIR:-/srv}
        node_version: ${USE_NODE_VERSION:-16.20.0}
        node_env: ${NODE_ENV:-development}
        debug: ${DEBUG:-yes}
        tz: ${TZ:-Etc/UTC}
        auth_user: ${AUTH_USER:?}
        auth_pass: ${AUTH_PASS:?}
    environment:
      SERVER_PORT: ${SERVER_PORT:-3033}
      SERVERLESS: ${SERVERLESS:-no}
      SERVER_HOST: ${SERVER_HOST:?}
      STORAGE: ${STORAGE:-STORAGE_SQLITE}
      SQLITE_DB: ${SQLITE_DB:-data.db}
      SQLITE_TABLE: ${SQLITE_TABLE:-tokens}
      DATA_FILE_DIR: ${DATA_FILE_DIR:?}
      DATA_FILE_NAME: ${DATA_FILE_NAME:-.secrets.db}
      JWT_SECRET: ${JWT_SECRET:?}
      OPENAI_API_ROOT: ${OPENAI_API_ROOT:-/v1}
      OPENAI_API_ORG: ${OPENAI_API_ORG}
    volumes:
      - ./node_modules:${WORKDIR:-/srv}/node_modules
      - ssl_keystore:/etc/ssl/certs/
      - ./docker/.db/:${DATA_FILE_DIR:?}/
      - ./src:${WORKDIR:-/srv}/src
    ports:
      - "${SERVER_PORT:-3033}:${SERVER_PORT:-3033}"
      - "9229:9229"
    user: node:node

  # Certbot service
  #
  # Chatbot: add service description
  certbot:
    image: "certbot/dns-${CB_DNS:?}:v${CB_VERSION:?}"
    entrypoint: certbot certonly -n -d ${SERVER_HOST:?}${WILDCARD_DOMAIN} --dns-${CB_DNS:?} ${CB_DRY_RUN} ${CB_AGREE_TOS}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      LINODE_CREDENTIALS_FILE: ${LINODE_CREDENTIALS_FILE:-~/.linode}
      DNS_DIGITALOCEAN_TOKEN: ${DNS_DIGITALOCEAN_TOKEN}
    volumes:
      - ./docker/certbot/etc/letsencrypt:/etc/letsencrypt
      - ssl_keystore:/var/lib/letsencrypt
      - ./docker/certbot/var/log/letsencrypt:/var/log/letsencrypt

  # SSL service
  #
  # On 1st run generates SSL certificate self-signed with user-specified CA.
  # Then they're available for server to mount from `docker/ssl/certs` folder.
  #
  # Chatbot: rewrite existing service description if needed
  myca:
    # image: lehcode/ssl-ca-certs:latest
    build:
      context: docker/myca/
      args:
        debug: ${DEBUG:-yes}
        key_len: ${KEY_LEN:-4096}
        days: ${CERT_DAYS:-365}
        ca_cn: ${MYCA_ORG_CN:-CAuth}
        server_cn: ${SERVER_HOST:?}
        host_user_uid: ${HOST_USER_UID:-1001}
        key_pass: ${MYCA_KEY_PASS}
    volumes:
      - ssl_keystore:/etc/ssl/certs/

volumes:
  soakp_db:
  ssl_keystore:
