export enum StatusMessage {
  CREATED = 'Created',
  FOUND = 'Found',
  INTERNAL_SERVER_ERROR = 'Internal server error',
  INVALID_KEY = 'Incorrect key supplied',
  INVALID_KEY_STORAGE = 'Invalid key storage',
  INVALID_OPENAI_KEY = 'OpenAI API key validation failed',
  INVALID_JWT = 'JWT validation failed',
  JWT_ACCEPTED = 'JWT accepted',
  JWT_ADDED = 'JWT added',
  JWT_EXPIRED = 'JWT expired',
  JWT_NOT_FOUND = 'JWT not found',
  JWT_NOT_SAVED = 'JWT not saved',
  JWT_UPDATED = 'JWT updated',
  GATEWAY_ERROR = 'Gateway error',
  LOADED_JWT_TOKEN = 'Loaded JWT token',
  NOT_AUTHORIZED = 'Not authorized',
  NOT_FOUND = 'Not found',
  RECEIVED_OPENAI_API_RESPONSE='Received OpenAI API response',
  SUCCESS = 'Success',
  UNKNOWN_ERROR = 'Unknown error',
  UPLOAD_ERROR = 'Upload error',
  WRONG_FILE_TYPE = 'Wrong file type',
  WRONG_REQUEST = 'Wrong Request'
}
